baseURL = "https://osanpozuki.github.io/tama-blog/"
languageCode = "jp"
title = "たま"
theme = "m10c"
googleAnalytics = "UA-135002662-1"
publishdir = "public"
[params]
  author="tama"
  description="駆け出しエンジニア"
  
[[params.social]]
  name = "github"
  url = "https://github.com/osanpozuki"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/osanpozuki"